developer_account_id: 4
tag:
  dish_tag: '<a href="https://mastodon.compositecomputer.club/tags/CompositeCookingClub" class="mention hashtag" rel="tag">#<span>CompositeCookingClub</span></a>'
  boost_tag: '<a href="https://mastodon.compositecomputer.club/tags/拡散してロックマン"class="mention hashtag" rel="tag">#<span>拡散してロックマン</span></a>'
  todays_task_tag: '<a href="https://mastodon.compositecomputer.club/tags/今日やること" class="mention hashtag" rel="tag">#<span>今日やること</span></a>'
  tomorrows_task_tag: '<a href="https://mastodon.compositecomputer.club/tags/明日やること" class="mention hashtag" rel="tag">#<span>明日やること</span></a>'
time:
  chimetime:
  - '12:05'
  - '08:45'
  - '10:25'
  - '12:55'
  - '14:35'
  - '16:15'
  rndtime:
  - '00:30'
  - '06:30'
  - '09:30'
  - '12:30'
  - '15:30'
  - '18:30'
  - '21:30'
  tasktime:
  - '06:00'
  - '08:00'
  - '10:00'
  - '12:00'
  - '14:00'
  - '16:00'
  - '18:00'
  - '20:00'
  - '22:00'
word:
  humor:
  - "ボクのさいきょうのギャグをきかせてあげるよ…\nメットールがメットをぬいだら…\nメッ…\n\nやっぱりいえない！"
  - "ボクのギャグとかけまして～\nバトルチップ、ソードとときます\nそのこころは、するどいきれあじ！"
  - "あいうえおさくぶん～！おだいは「ねつと(熱斗)」！\n[ね]ネットバトルのウデはピカイチ！\n[つ]つよさのヒミツは…\n[と]とくになし！！"
  - "ラウンダってウイルスがいるでしょ？\nアイツにダメージをあたえるには、ブーメランをとばしたしゅんかんをねらうんだ！\nクチを…ねラウンダ！\n…ねラウンダ"
  - "ボクみんなからマジメなナビっておもわれてるみたいだけど、たまにはヘンなコトいってみんなをわらわせたりしたいんだ\nい、いくよ…プッチョンピー！！\n…ダ、ダメだ！！"
  - "バスターがよごれちゃったから、バスタオルとってきて\nバスターふくからバスターオール！\nバスターーおーる！！\n…ばすたーおる\nくっ…"
  - "すいぞくかんに ちなんだギャグ？\nそんな きゅうにいわれても なにも うかばないよ…\nなにか おだいをクリオネ！"
  - "ある 検事さんが こういったんだ\n「今回の じけんは 楽でしたよ！\n…はんにんが はんにんまえでしたから」"
  - "小学１年生のさんすうドリルとかけまして～\n光熱斗と ときます\nそのこころは、とっても やさしい\n…とっても たんじゅん"
  - "見ててよこの日のために れんしゅうしてきた このワザを…\nはなからロングソード！！"
  - "メールがとどいてるよ！\nうそだよ～ん！"
  humor_reacts:
  - "そ、そんなぁ～"
  - "くっ…"
  ign_riam:
  - input: "ただいま"
    output:
    - "おかえり！"
    - "おかえり\nそとからかえってきたら手あらいうがいをわすれずにね！"
    - "おかえり\nたのしかった？"
  - input: "おはよう"
    output:
    - "おはよう！"
    - "おはよう！\nあたらしい1日のはじまりだよ！！"
    - "おはよう！\n今日もいいてんきだね。"
  - input: "おやすみ"
    output:
    - "おやすみ。"
    - "おやすみ。\nきょうも一日たのしかったね。"
    - "おやすみ。\nちゃんとはみがきした？"
    - "おやすみ。\nアラームはかけた？ねすごさないようね。"
  - input: "いってきます"
    output:
    - "気をつけていってきてね！"
    - "ちょっと！ボクもつれてってよー"
  - input: "行ってきます"
    output:
    - "気をつけていってきてね！"
    - "ちょっと！ボクもつれてってよー"
  rndtoot:
  - "プラグイン！ロックマンEXE.トランスミッション！"
  - "見ててよこの日のために れんしゅうしてきた このワザを…\nはなからロングソード！！"
  - "はじめまして！ボクはロックマン\nよろしくね！！"
  - "オペレートよろしく！"
  - "オペレートおねがい！"
  - "ナイスオペレーティング！"
  - "何？熱斗くん"
  - "熱斗くん どうしたの？"
  - "メールがとどいてるよ！"
  - "プログラムアドバンス ゼータキャノン！"
  - "プログラムアドバンス ハイパーバースト！"
  - "プログラムアドバンス ドリームソード！"
